apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loggingoperators.logging.kubesphere.io
  labels:
    app: {{ template "logging-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  group: logging.kubesphere.io
  names:
    kind: LoggingOperator
    listKind: LoggingOperatorList
    plural: loggingoperators
    singular: loggingoperator
  scope: Cluster
  version: v1alpha1